// import Icons
import 'bootstrap-icons/font/bootstrap-icons.css';

// import Bootstrap
import 'bootstrap/dist/css/bootstrap.css';

// import AOS CSS
import 'aos/dist/aos.css';
import AuthProvider from './context/AuthProvider';
// import { getServerSession } from "next-auth";
// import { Session } from "next-auth";
import type { Metadata } from "next";
import { EB_Garamond, Geist, Geist_Mono } from "next/font/google";
import { Header } from '@/app/components/Header';

import "./variables.css";
import "./globals.css";
import DownloadJsonButton from './components/DownloadJsonButton';
import DataTable from './components/DataTable';
import UploadForm from './components/UploadForm';

const ebGaramond = EB_Garamond({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
            <Header/>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
